Migrate to matterjs
mfucci/node-matter pull request #130
Opened 2022-11-16 07:33 UTC by mfucci

2022-11-16 07:40 UTC, mfucci commented on src/matter/cluster/AccessControlCluster.ts
>   */
This is one way to use it: deconstruct tlv into the base classes and reference them directly.

2022-11-16 07:40 UTC, mfucci commented on src/matter/cluster/AccessControlCluster.ts
> -const AccessControlEntryT = ObjectT({
This is a 2nd way: keep the name space

2022-11-16 07:40 UTC, mfucci commented on src/matter/cluster/AccessControlCluster.ts
> +        accessControlEntryChanged: Event(0, EventPriority.Info, AccessChangeEvent(TlvAccessControlEntry)), /* readAcl: AccessLevel.Administer */
The original code was incorrect here...

2022-11-30 02:52 UTC, mfucci commented
@Apollon77 Did you find time to review this?

2022-11-30 06:01 UTC, Apollon77 commented
Oohh overseen. Will do today

2022-11-30 17:33 UTC, Apollon77 requested changes
Only  sa small thing, rest wow ... a biggie but an awesome step forward

2022-11-30 17:33 UTC, Apollon77 commented on src/matter/cluster/GroupsCluster.ts
> -         * @see {@link MatterApplicationClusterSpecificationV1_0} § 1.3.7.1
why you removed the specs links here

2022-11-30 17:33 UTC, Apollon77 commented on src/matter/cluster/GroupsCluster.ts
> -         * @see {@link MatterApplicationClusterSpecificationV1_0} § 1.3.7.1
or is it enough to have th general chapter on top?

2022-12-01 01:22 UTC, mfucci commented
All comments addressed!

2022-12-01 08:48 UTC, Apollon77 approved these changes
Approved. Thank you. I think I will have time next week to continue cluster efforts ... so perfect timing :-)

2022-12-01 15:56 UTC, merged