Add missing global attributes
mfucci/node-matter pull request #203
Opened 2023-01-26 11:37 UTC by Apollon77

2023-01-26 11:37 UTC, Apollon77 commented on src/matter/cluster/Cluster.ts
>  }
I need to typing support in how I need to specify them here ...

2023-01-28 08:02 UTC, mfucci requested changes
Also add attributes in GlobalAttributes

2023-01-28 08:50 UTC, Apollon77 commented
@mfucci please re-check. Added typing (used as you proposed directly ....) and Todo

2023-01-30 07:03 UTC, mfucci approved these changes

2023-01-30 07:04 UTC, merged