Forward the PacketHeader to invoke command handler
mfucci/node-matter pull request #206
Opened 2023-01-26 16:28 UTC by Apollon77

For Group clusters (and also opthrs) we need to be able to access information from the package header when processing commands. In fact mainly the "request type" (multicast/unicast) and "is it a group request" is relevant based on the current knowledge but it should also not hurt to make all data available.

In fact yes we could limit it.

Additionally: I now called it "packetHeader", but "context" or such a term would also be an option. What do you think

2023-01-30 07:17 UTC, mfucci requested changes

2023-01-30 07:17 UTC, mfucci commented on src/matter/cluster/server/CommandServer.ts
> +        const response = await this.handler(request, session, packetHeader);
Let's pass the whole message

2023-02-01 07:46 UTC, Apollon77 commented
@mfucci adjusted as discussed

2023-02-04 20:32 UTC, mfucci approved these changes

2023-02-04 22:17 UTC, merged