Initial commit of Temperature Measurement Cluster (Issue #211)
mfucci/node-matter pull request #235
Opened 2023-02-09 20:29 UTC by JimBuzbee

Tested on Google Home with live temperature data.

2023-02-10 00:59 UTC, mfucci submitted a review, later dismissed

2023-02-10 07:57 UTC, Apollon77 requested changes
lets have the main cluster JSDoc trying to have the essense what the cluster does :-)

2023-02-10 07:57 UTC, Apollon77 commented on src/matter/cluster/TemperatureMeasurementCluster.ts
> + * Attributes for Temperature Measurement.
```suggestion
 * This cluster provides an interface to temperature measurement functionality.
```

2023-02-10 07:57 UTC, Apollon77 commented on src/matter/cluster/TemperatureMeasurementCluster.ts
> +       maxMeasuredValue: Attribute(2, TlvNullable(TlvInt16.bound({ max: 32767 }))),
max "could" be removed here because it is the natural Signed Int 16bit maximum alreayd used.

2023-02-11 13:37 UTC, Apollon77 commented
@JimBuzbee If you are ready for recheck just click on the "circle arrows" beside my name above in the reviewer list

2023-02-11 14:36 UTC, JimBuzbee commented
I think I did it, and accepted, but it's red for me?

![image](https://user-images.githubusercontent.com/4139136/218263681-6d660cea-d15c-4093-b090-8a0bb085ec59.png)

2023-02-11 15:29 UTC, Apollon77 commented
Yes it still has the old result shown there. if you klick the "circle button" then it disapears and I get an email ... but I check now

2023-02-11 15:30 UTC, Apollon77 approved these changes

2023-02-11 15:30 UTC, merged