Do not throw strings
mfucci/node-matter pull request #238
Opened 2023-02-11 10:34 UTC by Apollon77

2023-02-12 06:53 UTC, Apollon77 commented
Change to a typed EndOfStreamError

2023-02-12 12:20 UTC, Apollon77 commented
@mfucci Seems we missed to click the ok button here ... Adjustments done, Ready for re-review

2023-02-13 04:17 UTC, mfucci requested changes

2023-02-13 04:17 UTC, mfucci commented on src/util/Stream.ts
>  export const END_OF_STREAM = "End-of-Stream";
You can delete this

2023-02-13 04:17 UTC, mfucci commented on src/util/Stream.ts
> +    constructor() {
You don't need a constructor, the class type is enough.

2023-02-13 21:04 UTC, Apollon77 commented
Adjusted

2023-02-19 07:22 UTC, mfucci approved these changes

2023-02-19 08:34 UTC, merged