First push of the Power Source Cluster.
mfucci/node-matter pull request #267
Opened 2023-03-09 17:30 UTC by JimBuzbee

First push of the Power Source Cluster. Derived from project-chip XML Note prefix added to BatCommonDesignationEnum keys as Spec called for numeric keys which are illegal under Typescript. Untested.

2023-03-09 19:25 UTC, Apollon77 requested changes

2023-03-09 19:25 UTC, Apollon77 commented on src/matter/cluster/PowerSourceCluster.ts
> +      Battery: BitFlag(1),
lowercase please, also below

2023-03-09 19:25 UTC, Apollon77 commented on src/matter/cluster/PowerSourceCluster.ts
> +      Status: Attribute(0x0000,TlvEnum<PowerSourceStatusEnum>()),
nit space after comma please (we have formatter soon) :-)

2023-03-09 19:25 UTC, Apollon77 commented on src/matter/cluster/PowerSourceCluster.ts
> +      Status: Attribute(0x0000,TlvEnum<PowerSourceStatusEnum>()),
And also here lowercase please

2023-03-09 20:25 UTC, JimBuzbee commented on src/matter/cluster/PowerSourceCluster.ts
> +const WiredFaultChangeEvent = <T>() => ({
Yeah 

= <T>() => ({

Kind of looks like a cat walked across the keyboard :-)  Was giving me some trouble satisfying the "event:" definition (as did TlvObject), but I was likely overthinking it.  New push on the way - hopefully got it right.

Good catch on the IDs - Fixed.

2023-03-10 14:49 UTC, Apollon77 approved these changes

2023-03-10 14:49 UTC, merged