Add an attribute listener fired even if the value doesn't change
mfucci/node-matter pull request #80
Opened 2022-10-24 00:20 UTC by mfucci

This attribute is meant to be used by local APIs

2022-10-24 07:53 UTC, Apollon77 commented on src/matter/cluster/server/AttributeServer.ts
> +            this.listeners.forEach(listener => listener(value, value));
sneaky ... was thinking ... stop ... should one not be this.value .... but yes both are the same *gg*

2022-10-24 07:59 UTC, Apollon77 reviewed
Why InteractionProtocol.ts is in here as "full new file"?

2022-10-24 07:59 UTC, Apollon77 commented on src/matter/interaction/SubscriptionHandler.ts
> +        attributes.forEach(({ attribute }) => attribute.addMatterListener(this.listener));
Should you bind the "this.listener" to "this"?

2022-10-24 20:19 UTC, mfucci commented
InteractionProtocol.ts : probably a side-effect of the squash. This file is rename in the base branch (to InteractionProtocol to make it consistent) and it was modified when changing the copyright notice.
Removed.

2022-10-25 07:57 UTC, Apollon77 requested changes

2022-10-25 07:57 UTC, Apollon77 commented on src/matter/interaction/SubscriptionHandler.ts
> +            this.updateTimer = Time.get().getTimer(setTimeout(() => this.sendUpdate(), this.minIntervalFloorMs - timeSinceLastUpdateMs);
should this not also be changed toTime.getTimer(...).start()... and also without a setTimeout in it?

2022-10-25 07:57 UTC, Apollon77 commented on src/matter/interaction/SubscriptionHandler.ts
> +        this.updateTimer = setTimeout(() => this.sendUpdate(), this.maxIntervalCeilingMs);
also here use timer.stop() to stop and not settimeout? (or is that not based on new Time stuff?)

2022-10-25 07:57 UTC, Apollon77 commented on src/matter/interaction/SubscriptionHandler.ts
> +        clearTimeout(this.updateTimer);
same here this.updateTimer.stop()

2022-10-25 21:12 UTC, mfucci commented
I merged the changes from the base branch and the random unrelated changes are not there anymore. Sorry about that.
Now the PR should be clean

2022-10-25 21:37 UTC, Apollon77 approved these changes
LGTM

2022-10-25 21:49 UTC, merged